### ISSUE TITLE
[FR] change download destination

### ISSUE THREAD

**Issue by ildar** [dnet/adsdroid#15]
Probably here: https://github.com/dnet/adsdroid/blob/f12ed6d8f4f27791a2797288d595bab515040d75/src/hu/vsza/adsdroid/PartList.java#L85
I like the app, are you going to support it further?

**Comment by dnet** [comment]
You got it right, it could be implemented there. The question is, what UI should be used for this?

AFAIK as Android has no system-wide/platform-provided _Save file_ UI like [common dialogs in Microsoft Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646960(v=vs.85).aspx), it's not a trivial move. Do you have an example maybe in another app that you think is intuitive and works well? I'd prefer if it's FLOSS, so that we could take the component as-is without having to reimplement it and/or face legal issues.

> I like the app, are you going to support it further?

For me, it's doing its job well, so I don't have plans of my own. However, I accept pull requests, and selectively implement feature requests, if I have the time. Is that a yes?

**Comment by ildar** [comment]
This is "yes-yes!". :)
Then could you please check if it works good? I can't get a datasheet with
https://github.com/dnet/adsdroid/releases/tag/v1.6.2
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ildar** [comment]
IMHO this doesn't need any UI: I suggest just using the standard
/sdcard/Download folder, or precisely,
`Environment.getExternalStorageDirectory()
+ "/"+Environment.DIRECTORY_DOWNLOADS+ "/"` but check API compat.
Source:
https://stackoverflow.com/questions/11351840/location-of-downloads-folder-for-devices-with-and-without-sd-card
