### ISSUE TITLE
[FR] catch a text as Share to ADSDroid

### ISSUE THREAD

**Issue by ildar** [dnet/adsdroid#17]
Need an intent for that...

**Comment by ildar** [comment]
Not fully what I expected: should also start searching.

**Comment by dnet** [comment]
But then you wouldn't be able to set the search mode. That's important since only the first 10 results are shown by ADS, so if the search term matches many false positives, the part you're looking for could be left out entirely. So there's no sensible default, the search mode is best to be chosen by the user, armed with the knowledge of how specific his/her search term is.

**Comment by ildar** [comment]
agreed
