### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [dnet/adsdroid#22]

**Comment by dnet** [comment]
Sure! If we're touching the logo/icon, could you do it in an [adaptive](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) version as well so that newer platforms can take advantage?

**Comment by waqasanwar94** [comment]
@dnet Hi sir would you explain some thing about app because it  looks like Advertisement app because of ADS written on logo icon and when i try to use its showing PDS files so for a good logo first you need to tell me about the app you can also tell me what type of logo you want if you have no idea then its ok

**Comment by ildar** [comment]
ALLDATASHEET.COM is the biggest online electronic component datasheets
search engine. (http://alldatasheet.com/)
This is the client for that site.

**Comment by dnet** [comment]
> ALLDATASHEET.COM is the biggest online electronic component datasheets search engine. (http://alldatasheet.com/)

...hence the name ADSdroid, where ADS is the abbreviation of **A**LL**D**ATA**S**HEET

**Comment by waqasanwar94** [comment]
ok, sir, i got your point and i will try my best for making an awesome logo.

**Comment by waqasanwar94** [comment]
i just check you have no license file so i am so sorry i cant make logo if there are no license file
thank you

**Comment by TacoTheDank** [comment]
not to make you guys feel like you've wasted time, but this guy has copy-pasted this same exact message in a whole bunch of other android projects (i know because i follow them) :/

**Comment by TacoTheDank** [comment]
the only thing thats changed at all is the text inside the quotation marks

**Comment by waqasanwar94** [comment]
@TacoTheDank shame on you 
how can you say this about my work even what you know about me?
like you some persons very cheap they try to beat anyone but cant that's why they jealous
no doubt i am making the logo for many projects that's why little bit late now you can get lose from here

![11](https://user-images.githubusercontent.com/38813945/40100525-a78e2212-58fd-11e8-887c-d40a749909a9.png)
![39764963-2d514fbe-52fa-11e8-879f-d3499848b192](https://user-images.githubusercontent.com/38813945/40100526-a7d08292-58fd-11e8-8e08-2f127005cafb.png)
![39851502-9365647a-5430-11e8-8d9c-27ae24c75b6c](https://user-images.githubusercontent.com/38813945/40100527-a8128606-58fd-11e8-86f4-52e41e37fd1a.jpg)
![39960594-05ade5ec-563f-11e8-85fc-13b2596c94dc](https://user-images.githubusercontent.com/38813945/40100528-a8552740-58fd-11e8-8078-0e191ee1b4ce.jpg)
![39960595-05ee29f4-563f-11e8-96fd-1aeee6d2f264](https://user-images.githubusercontent.com/38813945/40100530-a8978b1c-58fd-11e8-90bf-540aea0d3d79.jpg)
![39960596-06508e0a-563f-11e8-8363-4778d1c8e82f](https://user-images.githubusercontent.com/38813945/40100531-a8d89648-58fd-11e8-95de-4376a3831d38.jpg)
![39970204-111aa4f2-5701-11e8-831b-cf7f88fafe74](https://user-images.githubusercontent.com/38813945/40100533-a91af6b4-58fd-11e8-9d2e-0b8cc55a1831.png)
![40070556-dc2d773c-5887-11e8-8310-1e857b817e56](https://user-images.githubusercontent.com/38813945/40100534-a95c8214-58fd-11e8-8c55-043740b9a368.jpg)

**Comment by waqasanwar94** [comment]
![11](https://user-images.githubusercontent.com/38813945/40106909-6c95588e-5910-11e8-8b24-733df7130627.png)

Hi sir,
Here are some logos which i make for you please have a look and let me know which logo you like more and if you want any change i can just let me know 
thank  you

**Comment by dnet** [comment]
Thanks, these look nice. I'll discuss it with some friends and will get back to you.

**Comment by ildar** [comment]
@waqasanwar94 , are these all your logos?

**Comment by ildar** [comment]
Emm, #14 https://www.flaticon.com/free-icon/artificial-intelligence_820876

**Comment by dnet** [comment]
Continuing the list of @ildar

 - Number 6: https://www.flaticon.com/free-icon/cpu_204289
 - Number 9: https://www.flaticon.com/free-icon/cpu_167482
 - Number 11: https://www.flaticon.com/free-icon/cpu_900988

@waqasanwar94 do you have the necessary rights for these icons to be used by ADSdroid? What kind of attribution would this need? (To clarify the comment made by @ildar above.)

**Comment by dnet** [comment]
That sounds better. So to get this straight: if you give us one of these logos (with or without modifications) we can use it for the app even after you subscription with Flaticon ends -- right?

**Comment by TacoTheDank** [comment]
Read the basic license pdf anyways, never hurts

And some of these (like 6 and 10) can be used and downloaded for free if the proper credit to the creator is given

@waqasanwar94 my problem with you is that I don't like how you're referring to them as "your" logos (that you repeatedly stated you created), when you didn't actually make any of them

**Comment by dnet** [comment]
Unfortunately, the [license terms of Flaticon](https://profile.flaticon.com/license/premium) say otherwise: (emphasis mine)

> What you CAN DO: [...] You can use Flaticon Contents *during the rights period* world widely.

and

> What you CANNOT DO:
> - Sublicense, sell or rent any of Flaticon Contents (or a modified version of Flaticon Content).
> - Distribute Flaticon Contents unless it has been expressly authorized by Flaticon.

also

> In case of termination of the license, the User shall cease using Flaticon Content and will destroy every copy, whether total or partial, thereof.

So if you have a design you made yourself or have the rights to sublicense it to ADSdroid, I'd still like a new icon. But the Flaticon terms seem pretty clear to me and I'd like to avoid any legal problems.

**Comment by TacoTheDank** [comment]
@waqasanwar94 who the fuck said i was jealous lmao

and you're the one inadvertently trying to get people into possible legal trouble cause you wanna pass shit off as your own

**Comment by dnet** [comment]
Just so that people who arrive later to this thread understand what was going on (since @waqasanwar94  deleted all his comments and edited the issue description to a blank string), here are his original comments, reconstructed from the notification emails I got from GitHub.

### Tue, 15 May 2018 09:45:00 +0000 (UTC) (original issue description)

Hello, @dnet I want to contribute in "adsdroid" so i want to design a new logo for "adsdroid" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery
https://www.facebook.com/waqasanwar68

### Tue, 15 May 2018 04:18:00 -0700

@dnet Hi sir would you explain some thing about app because it  looks like Advertisement app because of ADS written on logo icon and when i try to use its showing PDS files so for a good logo first you need to tell me about the app you can also tell me what type of logo you want if you have no idea then its ok

### Tue, 15 May 2018 04:55:52 -0700

ok, sir, i got your point and i will try my best for making an awesome logo.

### Tue, 15 May 2018 16:44:34 +0000 (UTC)

i just check you have no license file so i am so sorry i cant make logo if there are no license file 

thank you

### Tue, 15 May 2018 23:39:21 -0700

@TacoTheDank shame on you
how can you say this about my work even what you know about me?
like you some persons very cheap they try to beat anyone but cant that's why they jealous
no doubt i am making the logo for many projects that's why little bit late now you can get lose from here

![11](https://user-images.githubusercontent.com/38813945/40100525-a78e2212-58fd-11e8-887c-d40a749909a9.png)
![39764963-2d514fbe-52fa-11e8-879f-d3499848b192](https://user-images.githubusercontent.com/38813945/40100526-a7d08292-58fd-11e8-8e08-2f127005cafb.png)
![39851502-9365647a-5430-11e8-8d9c-27ae24c75b6c](https://user-images.githubusercontent.com/38813945/40100527-a8128606-58fd-11e8-86f4-52e41e37fd1a.jpg)
![39960594-05ade5ec-563f-11e8-85fc-13b2596c94dc](https://user-images.githubusercontent.com/38813945/40100528-a8552740-58fd-11e8-8078-0e191ee1b4ce.jpg)
![39960595-05ee29f4-563f-11e8-96fd-1aeee6d2f264](https://user-images.githubusercontent.com/38813945/40100530-a8978b1c-58fd-11e8-90bf-540aea0d3d79.jpg)
![39960596-06508e0a-563f-11e8-8363-4778d1c8e82f](https://user-images.githubusercontent.com/38813945/40100531-a8d89648-58fd-11e8-95de-4376a3831d38.jpg)
![39970204-111aa4f2-5701-11e8-831b-cf7f88fafe74](https://user-images.githubusercontent.com/38813945/40100533-a91af6b4-58fd-11e8-9d2e-0b8cc55a1831.png)
![40070556-dc2d773c-5887-11e8-8310-1e857b817e56](https://user-images.githubusercontent.com/38813945/40100534-a95c8214-58fd-11e8-8c55-043740b9a368.jpg)

### Wed, 16 May 2018 01:53:32 -0700

![11](https://user-images.githubusercontent.com/38813945/40106909-6c95588e-5910-11e8-8b24-733df7130627.png)

Hi sir,

Here are some logos which i make for you please have a look and let me know which logo you like more and if you want any change i can just let me know

thank  you

### Wed, 16 May 2018 07:22:52 -0700

@ildar if i sending you, of course, all are my logos when you choose any one i will also send you PNG, PSD, PDF  e.t.c all files  just let me know after your discussion

### Thu, 17 May 2018 01:20:40 -0700

i have full rights to use any logo because i am paid a member of Flaticon you can see proofs below

![screenshot_1](https://user-images.githubusercontent.com/38813945/40165266-f8c0178a-59d4-11e8-96d5-134501898771.png)

### Thu, 17 May 2018 02:20:33 -0700

of course sir you can use it

### Thu, 17 May 2018 07:44:15 -0700

@TacoTheDank i dont know what is your problem you are a shameless person
if you cant do anything for anyone so why are you jealous if anyone doing
peoples  like you just can jealous because they cant reach other levels please take you dick from here and get lost
