### ISSUE TITLE
Promoting your app in electronics forums

### ISSUE THREAD

**Issue by timofonic** [dnet/adsdroid#9]
Hello.

I think your app is very interesting, but needs more users. Those can provide feedback, give issues and maybe some of them are able to cover too.

I usually visit eevblog, allaboutcircuits, Dangerous Prototypes and not much else.

I suggest you try do a nice formatted post with nice text, the reasons if the app, some screenshots, github site and where to download it from.

You can put it in XDA too :)

**Comment by dnet** [comment]
Actually, it's been promoted at those places, when it was new. I've written a [blogpost](http://techblog.vsza.hu/posts/Unofficial_Android_app_for_alldatasheet.com.html) back then and it was featured (among others) in
 - Hackaday: http://hackaday.com/2012/04/18/android-app-review-adsdroid-gives-you-every-datasheet-ever/
 - XDA: http://www.xda-developers.com/access-any-datasheet-on-your-android/
 - and several other smaller sites.

Since nothing really happened since (smaller fixes and newer Android designs are no big changes) the original blogpost is still relevant, feel free to post it anywhere. The QR code and download URL always points to the latest version.

**Comment by timofonic** [comment]
It's okay. I can promote it and even translate it to Spanish :D

But what about active feedback? I can try it, but it's better if AdsDroid developer(s) are aware of the comments and participate.

- With enough participation, an Open Source section with more granularity could be created in them by the moderators.
* The thread could be stickied and appear at the top of the forum section to not get lost.

- There are a bunch of very popular and active electronics communities about different topics or levels.
* These can provide different kind of suggestions and testing.
* It's difficult to find people with enough good skills at both electronics and programming.

**Comment by dnet** [comment]
So far I'm the only developer of ADSdroid, and I appreciate if anyone (including you) do either commenting or monitoring on any forum regarding this app, but for feedback regarding issues (bugs, feature requests, etc.) I'd prefer people submitting these into the GitHub issue tracker of this project. This way, issues and source code is 1:1 correlated, participants are notified by email automatically, and I don't have to monitor forum threads.
